baseurl = "https://smenonw.github.io/"
canonifyurls = true
googleAnalytics = ""
languageCode = "en-us"
metadataformat = "yaml"
theme = "hugo-material-docs"
title = "WETHOD / Learning Center"
[blackfriday]
fractions = true
plainIDAnchors = true
smartDashes = true
smartypants = true
disableKinds = ['taxonomy', 'term']
[[menu.company]]
name = "Order Plan"
url = "order-plan/"
weight = 10
[[menu.company]]
name = "Invoice Plan"
url = "invoice-plan/"
weight = 9
[[menu.company]]
name = "Capex"
url = "capex/"
weight = 8
[[menu.company]]
name = "Marketing"
url = "marketing/"
weight = 7
[[menu.company]]
name = "G & A"
url = "general-admin/"
weight = 6
[[menu.company]]
name = "Payroll"
url = "payroll/"
weight = 5
[[menu.company]]
name = "Gross Margin"
url = "gross-margin/"
weight = 4
[[menu.company]]
name = "External Costs"
url = "external-costs/"
weight = 3
[[menu.company]]
name = "Revenues"
url = "revenues/"
weight = 2
[[menu.company]]
name = "Profit & Loss"
url = "profit-loss/"
weight = 1
[[menu.group]]
name = "Setup"
url = "group-setup/"
weight = 3
[[menu.group]]
name = "Revenues"
url = "group-revenues/"
weight = 2
[[menu.group]]
name = "Profit & Loss"
url = "group-profit-loss/"
weight = 1
[[menu.main]]
name = "Settings"
url = "settings/"
weight = 11
[[menu.main]]
name = "Finance"
url = "finance/"
weight = 10
[[menu.main]]
name = "Reports"
url = "reports/"
weight = 9
[[menu.main]]
name = "Friday"
url = "friday/"
weight = 8
[[menu.main]]
name = "Planning"
url = "planning/"
weight = 7
[[menu.main]]
name = "Budget"
url = "budget/"
weight = 6
[[menu.main]]
name = "Pipeline"
url = "pipeline/"
weight = 5
[[menu.main]]
name = "Alerts"
url = "alerts/"
weight = 4
[[menu.main]]
name = "Dashboard"
url = "dashboard/"
weight = 3
[[menu.main]]
name = "Desk"
url = "desk/"
weight = 2
[[menu.main]]
name = "Getting started"
url = "getting-started/"
weight = 1
[[menu.other]]
name = "Glossary"
url = "glossary/"
weight = 2
[[menu.other]]
name = "FAQ"
url = "faq/"
weight = 1
[[menu.new]]
name = "New"
url = "new/new1/"
weight = 1
 [menu.new.params]
    class = 'highlight'
[[menu.new]]
name = "New-2"
url = "new/new2/"
weight = 2
 [menu.new.params]
    class = 'highlight'
[params]
author = "Andrea Tombolato"
copyright = ""
custom_css = ["stylesheets/custom-style.css"]
custom_js = []
description = "A lean multi-project management platform that fosters the autonomy and ownership of every team member at any level."
favicon = "images/favicon.ico"
highlight_css = ""
logo = "images/logo.png"
permalink = "#"
provider = ""
repo_url = ""
version = ""
[params.font]
code = "Ubuntu Mono"
text = "Helvetica"
[params.palette]
accent = "teal"
primary = "black"
[social]
email = "info@wethod.com"
github = ""
twitter = ""
