---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Group
- type: directory
  path: content/payroll
  label: Payroll
  create: all
  match: "**/*"
- type: directory
  path: content/marketing
  label: Marketing
  create: all
  match: "**/*"
- type: directory
  path: content/external-costs
  label: External costs
  create: all
  match: "**/*"
- type: directory
  path: content/profit-loss
  label: Profit loss
  create: all
  match: "**/*"
- type: directory
  path: content/general-admin
  label: General admin
  create: all
  match: "**/*"
- type: directory
  path: content/revenues
  label: Revenues
  create: all
  match: "**/*"
- type: directory
  path: content/invoice-plan
  label: Invoice plan
  create: all
  match: "**/*"
- type: directory
  path: content/order-plan
  label: Order plan
  create: all
  match: "**/*"
- type: directory
  path: content/capex
  label: Capex
  create: all
  match: "**/*"
- type: directory
  path: content/group-setup
  label: Group Setup
  create: all
  match: "**/*"
- type: directory
  path: content/group-revenues
  label: Group Revenues
  create: all
  match: "**/*"
- type: directory
  path: content/group-profit-loss
  label: Group Profit & Loss
  create: all
  match: "**/*"
- type: directory
  path: content/alerts
  label: Alerts
  create: all
  match: "**/*"
- type: directory
  path: content/budget
  label: Budget
  create: all
  match: "**/*"
- type: directory
  path: content/reports
  label: Reports
  create: all
  match: "**/*"
- type: directory
  path: content/settings
  label: Settings
  create: all
  match: "**/*"
- type: directory
  path: content/finance
  label: Finance
  create: all
  match: "**/*"
- type: directory
  path: content/faq
  label: Faq
  create: all
  match: "**/*"
- type: directory
  path: content/glossary
  label: Glossary
  create: all
  match: "**/*"
- type: directory
  path: content/friday
  label: Friday
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/getting-started
  label: Getting started
  create: all
  match: "**/*"
- type: directory
  path: content/planning
  label: Planning
  create: all
  match: "**/*"
- type: directory
  path: content/pipeline
  label: Pipeline
  create: all
  match: "**/*"
- type: directory
  path: content/dashboard
  label: Dashboard
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
instant_preview: 
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.20.2
  preview_output_directory: public
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
version: 0.20.2
